// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef BASEROULANTE_H
#define BASEROULANTE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class BaseRoulante: public frc::Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<frc::SpeedController> baseDroite2;
	std::shared_ptr<frc::SpeedController> baseDroite1;
	std::shared_ptr<frc::SpeedControllerGroup> baseDroite;
	std::shared_ptr<frc::SpeedController> baseGauche1;
	std::shared_ptr<frc::SpeedController> baseGauche2;
	std::shared_ptr<frc::SpeedControllerGroup> baseGauche;
	std::shared_ptr<frc::AnalogGyro> gyro;
	std::shared_ptr<frc::Encoder> encodeurDroit;
	std::shared_ptr<frc::Encoder> encodeurGauche;
	std::shared_ptr<frc::DoubleSolenoid> ballshiffter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	bool vitesse1;

public:
	BaseRoulante();
	void InitDefaultCommand() override;
	void Periodic() override;

	void Drive(double gauche, double droite);
	void ActiverVitesse1();
	void ActiverVitesse2();
	void ChangerVitesse();

	int GetEncodeurDroit();
	int GetGyro();
	void ResetPID();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
