// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Pince.h"
#include "../RobotMap.h"
#include "WPILib.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

Pince::Pince() : frc::Subsystem("Pince")
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    roues = RobotMap::pinceRoues;
    verin = RobotMap::pinceVerin;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    pinceOuverte = false;
}

void Pince::InitDefaultCommand()
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void Pince::Periodic()
{

}

void Pince::Ouvrir()
{
	verin->Set(frc::DoubleSolenoid::Value::kReverse);
	pinceOuverte = true;
}

void Pince::Fermer()
{
	verin->Set(frc::DoubleSolenoid::Value::kForward);
	pinceOuverte = false;
}

void Pince::ChangerPosition()
{
	if(pinceOuverte)
	{
		this->Fermer();
	}
	else
	{
		this->Ouvrir();
	}
}

void Pince::Aspirer()
{
	roues->Set(0.5);
}

void Pince::Ejecter()
{
	roues->Set(-1);
}

void Pince::Stop()
{
	roues->Set(0);
}
