// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AjusterPivot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AjusterPivot::AjusterPivot(): Command()
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pivot.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	pov = 0;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR


void AjusterPivot::Initialize()
{
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
    Robot::pivot->Enable();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZE
}

void AjusterPivot::Execute()
{
	pov = Robot::oi->getJoystick1()->GetPOV();

	if(pov == 0)
	{
		Robot::pivot->SetSetpointRelative(12);
	}
	else if(pov == 180)
	{
		Robot::pivot->SetSetpointRelative(-12);
	}
}

bool AjusterPivot::IsFinished()
{
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ISFINISHED
	return false;
}

void AjusterPivot::End()
{

}

void AjusterPivot::Interrupted()
{

}
