// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AspirerCube.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AspirerCube::AspirerCube() : frc::TimedCommand(m_timeout) {
    // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pince.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

void AspirerCube::Initialize()
{

}

void AspirerCube::Execute()
{
	Robot::pince->Aspirer();

	if(this->TimeSinceInitialized() > m_timeout - m_dureeApresFermeture)
	{
		Robot::pince->Fermer();
	}
}

void AspirerCube::End()
{
	Robot::pince->Stop();
}

void AspirerCube::Interrupted()
{
	this->End();
}
