// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "AutoMilieu.h"

#include "AspirerCube.h"
#include "EjecterCube.h"
#include "PIDLigneDroite.h"
#include "PIDVirage.h"
#include "SetPivotSetpoint.h"

void AutoMilieu::Init(char coteSwitch)
{
	if (coteSwitch == 'L')
	{
		rotation1et8 = -35;
		rotation2et7 = 35;
		rotation3et5 = 74;
		rotation4et6 = -83;
	}
	else
	{
		rotation1et8 = 35;
		rotation2et7 = -35;
		rotation3et5 = -74;
		rotation4et6 = 83;
	}
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

AutoMilieu::AutoMilieu()
{
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	AddSequential(new PIDLigneDroite(30));
	AddSequential(new PIDVirage(rotation1et8));
	AddSequential(new PIDLigneDroite(195));
	AddSequential(new PIDVirage(rotation2et7));
	AddSequential(new SetPivotSetpoint(Pivot::SWITCH_AVANT));
	AddSequential(new EjecterCube());
	AddSequential(new PIDLigneDroite(-80));
	AddSequential(new PIDVirage(rotation3et5));
	AddSequential(new PIDLigneDroite(110));
	AddSequential(new PIDVirage(rotation4et6));
	AddSequential(new SetPivotSetpoint(Pivot::ECHANGEUR_AVANT));
	AddParallel(new AspirerCube());
	AddSequential(new PIDLigneDroite(50));
	AddSequential(new PIDLigneDroite(-50));
	AddSequential(new SetPivotSetpoint(Pivot::SWITCH_AVANT));
	AddSequential(new PIDVirage(rotation3et5));
	AddSequential(new PIDLigneDroite(-100));
	AddSequential(new PIDVirage(rotation4et6));
	AddSequential(new PIDLigneDroite(80));
	AddSequential(new EjecterCube());

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
