// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "DriveWithJoystick.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

DriveWithJoystick::DriveWithJoystick(): frc::Command()
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::baseRoulante.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

	y = 0;
	z = 0;
	vitesseGauche = 0;
	vitesseDroite = 0;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

void DriveWithJoystick::Initialize()
{

}

void DriveWithJoystick::Execute()
{
	y = Robot::oi->getJoystick1()->GetY();
	z = Robot::oi->getJoystick1()->GetZ();

	if (y < 0.2 && y > -0.2)
	{
		y = 0;
	}
	if (z < 0.2 && z > -0.2)
	{
		z = 0;
	}

	vitesseGauche = y - 0.5 * z;
	vitesseDroite = y + 0.5 * z;

	Robot::baseRoulante->Drive(vitesseGauche, vitesseDroite);
}

bool DriveWithJoystick::IsFinished()
{
    return false;
}

void DriveWithJoystick::End()
{
	Robot::baseRoulante->Drive(0,0);
}

void DriveWithJoystick::Interrupted()
{
	this->End();
}
