// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "EjecterCube.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

EjecterCube::EjecterCube() : frc::TimedCommand(m_timeout)
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pince.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

void EjecterCube::Initialize()
{

}

void EjecterCube::Execute()
{
	Robot::pince->Ejecter();
}

void EjecterCube::End()
{
	Robot::pince->Ouvrir();
	Robot::pince->Stop();
}

void EjecterCube::Interrupted()
{
	Robot::pince->Stop();
}
